# Generated by Django 3.2 on 2023-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="titles",
            name="rating",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="titles",
            name="genre",
            field=models.ManyToManyField(
                related_name="title", to="reviews.Genres"
            ),
        ),
    ]
