# Generated by Django 3.2 on 2023-08-18 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_auto_20230818_0611"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Genres",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Categories",
            new_name="Genre",
        ),
        migrations.RenameModel(
            old_name="Titles",
            new_name="Title",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр"},
        ),
    ]
