# Generated by Django 3.2 on 2023-08-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_auto_20230818_1016"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("name",),
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ("name",),
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                unique=True, verbose_name="Уникальный слаг"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(
                unique=True, verbose_name="Уникальный слаг"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titles",
                to="reviews.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                related_name="titles", to="reviews.Genre", verbose_name="Жанр"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="title",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=None, null=True, verbose_name="Рейтинг"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Дата выхода"),
        ),
    ]
