# Generated by Django 3.2 on 2023-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0008_alter_review_author"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("author", "title"),
                name="one_review_for_title_per_author",
            ),
        ),
    ]
