# Generated by Django 3.2 on 2023-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0009_review_one_review_for_title_per_author"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="one_review_for_title_per_author",
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("author", "title"), name="unique_author_review"
            ),
        ),
    ]
