# Generated by Django 3.2 on 2023-08-26 14:00

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0010_auto_20230819_1828"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.RemoveField(
            model_name="title",
            name="rating",
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(
                validators=[reviews.validators.validate_year],
                verbose_name="Дата выхода",
            ),
        ),
    ]
