# Generated by Django 3.2 on 2023-08-26 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0011_auto_20230826_1700"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenreTitle",
        ),
    ]
